### ISSUE TITLE
RegExp error on server launch

### ISSUE THREAD

**Issue by dxandersz** [dxandersz/errortracker#2]
david@Petunia:~/Desktop/General_Assembly/errortracker$ npm start

> errortracker@1.0.0 start /home/david/Desktop/General_Assembly/errortracker
> node server.js

/home/david/Desktop/General_Assembly/errortracker/node_modules/path-to-regexp/index.js:128
  return new RegExp(path, flags);
         ^

SyntaxError: Invalid regular expression: /^\/(?:([^\/]+?))[0-9]+)\/?$/: Unmatched ')'
    at new RegExp (<anonymous>)
    at pathtoRegexp (/home/david/Desktop/General_Assembly/errortracker/node_modules/path-to-regexp/index.js:128:10)
    at new Layer (/home/david/Desktop/General_Assembly/errortracker/node_modules/express/lib/router/layer.js:45:17)
    at Function.route (/home/david/Desktop/General_Assembly/errortracker/node_modules/express/lib/router/index.js:494:15)
    at Function.proto.(anonymous function) [as get] (/home/david/Desktop/General_Assembly/errortracker/node_modules/express/lib/router/index.js:509:22)
    at Object.<anonymous> (/home/david/Desktop/General_Assembly/errortracker/routes/user-router.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! errortracker@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the errortracker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2020-10-04T13_34_01_193Z-debug.log

**Comment by pmacaluso3** [comment]
In user-router.js line 8, the string needs to be `'/:id([0-9]+)'`. It was missing an opening parentheses. When I made this change locally, the server starts without this error.
